# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  consumer:
    image: consumer
    build:
      context: .
      dockerfile: ./Consumer/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5102:5102
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
